# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Release Version"
        required: true
      description: 
        description: "Release Description"
        required: true
        default: ''
  

name: Java CI with Maven


jobs:    
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.26.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CUSTOM_TAG: ${{ github.event.inputs.version }}
    - name: Build with Maven
      run: | 
       mvn -B package --file pom.xml
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        name: Release ${{ github.event.inputs.version }}
        body: ${{ github.event.inputs.description }}
        files: target/*.jar
        tag_name: v${{ github.event.inputs.version }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
